-- MySQL Script generated by MySQL Workbench
-- Sat Aug 24 23:10:59 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`articulo` (
  `id_articulo` INT NOT NULL AUTO_INCREMENT,
  `idcategoria_fk` INT NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`id_articulo`),
  INDEX `fk_articulo_categoria1_idx` (`idcategoria_fk` ASC),
  CONSTRAINT `fk_articulo_categoria1`
    FOREIGN KEY (`idcategoria_fk`)
    REFERENCES `mydb`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`boleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`boleta` (
  `id_boleta` INT NOT NULL AUTO_INCREMENT,
  `serie` VARCHAR(5) NULL,
  `numero` VARCHAR(10) NULL,
  `archivo` BLOB NULL,
  PRIMARY KEY (`id_boleta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gasto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gasto` (
  `id_gasto` INT NOT NULL AUTO_INCREMENT,
  `idarticulo_fk` INT NOT NULL,
  `idboleta_fk` INT NULL,
  `fecha` DATETIME NULL,
  `gasto` DOUBLE NULL,
  PRIMARY KEY (`id_gasto`),
  INDEX `fk_gasto_articulo1_idx` (`idarticulo_fk` ASC),
  INDEX `fk_gasto_boleta1_idx` (`idboleta_fk` ASC),
  CONSTRAINT `fk_gasto_articulo1`
    FOREIGN KEY (`idarticulo_fk`)
    REFERENCES `mydb`.`articulo` (`id_articulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gasto_boleta1`
    FOREIGN KEY (`idboleta_fk`)
    REFERENCES `mydb`.`boleta` (`id_boleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
